# Example configuration
# This assumes the host has 14 cores. Logical (HT) cores should be excluded as they are automatically accounted for.
# See `ProcessConfiguration` at https://github.com/jaszhix/wincontrol/blob/master/types/wincontrol/index.d.ts
# for all possible configuration options.

interval: 120000
logging: true
logPerProcessAndRule: true
logLevel: info
fullscreenPriority: true

affinities:
  - name: systemLow
    ranges: [[12, 13]]
  - name: systemHigh
    ranges: [[11, 13]]
  - name: systemVeryHigh
    ranges: [[0, 1], [11, 13]]
  - name: suppressed
    ranges: [[10]]
  - name: foregroundLow
    ranges: [[5, 9]]
  - name: foregroundMedium
    ranges: [[3, 9]]
  - name: foregroundHigh
    ranges: [[2, 9]]
  - name: foregroundVeryHigh
    ranges: [[0, 9]]
  - name: full
    ranges: [[0, 13]]

profiles:
  - name: servicesPriorityOnlyLow
    affinity: full
    cpuPriority: belowNormal
    pagePriority: normal
    ioPriority: low
    processes:
      - WindowsInternal.ComposableShell.Experiences.TextInput.InputApp

  # Example using disableIfRunning. OfficeClickToRun is only needed while an Office app runs,
  # but otherwise consumes CPU resources in the background.
  - name: terminateClickToRun
    terminationDelay: 1
    disableIfRunning:
      - EXCEL
      - MSACCESS
      - MSPUB
      - OUTLOOK
      - POWERPNT
      - WINWORD
    processes:
      - OfficeClickToRun
