# Example configuration
# This assumes the host has 14 cores. Logical (HT) cores should be excluded as they are automatically accounted for.
# See `ProcessConfiguration` at https://github.com/jaszhix/wincontrol/blob/master/types/wincontrol/index.d.ts
# for all possible configuration options.

interval: 60000
logging: true
detailedLogging: false
consoleLogging: false
logLevel: info
detectConfigChange: true
fullscreenPriority: true

affinities:
  - name: systemLow
    ranges: [[12, 13]]
  - name: systemHigh
    ranges: [[11, 13]]
  - name: systemVeryHigh
    ranges: [[0, 1], [11, 13]]
  - name: suppressed
    ranges: [[10]]
  - name: foregroundLow
    ranges: [[5, 9]]
  - name: foregroundMedium
    ranges: [[3, 9]]
  - name: foregroundHigh
    ranges: [[2, 9]]
  - name: foregroundVeryHigh
    ranges: [[0, 9]]
  - name: full
    ranges: [[0, 13]]

profiles:
  - name: servicesPriorityOnlyLow
    affinity: full
    cpuPriority: belowNormal
    pagePriority: normal
    ioPriority: low
    processes:
      - WindowsInternal.ComposableShell.Experiences.TextInput.InputApp

  # Example using the running condition. OfficeClickToRun is only needed while an Office app runs,
  # but otherwise consumes CPU resources in the background.
  - name: terminateClickToRun
    terminationDelay: 1
    if:
      condition: running
      forProcesses:
        - EXCEL
        - MSACCESS
        - MSPUB
        - OUTLOOK
        - POWERPNT
        - WINWORD
      then: disable
    processes:
      - OfficeClickToRun

  # Example using the fullscreenOverrideActive condition. If focused fullscreen applications are
  # given high priority (fullscreenPriority option), and one currently is focused, then give the
  # Steam process lower priority.
  - name: steam
    affinity: foregroundMedium
    cpuPriority: belowNormal
    pagePriority: belowNormal
    ioPriority: low
    processes:
      - Steam
    if:
      condition: 'fullscreenOverrideActive'
      # forProcesses: ... also able to restrict this condition to certain applications.
      then:
        affinity: suppressed
        cpuPriority: belowNormal
        pagePriority: belowNormal
        ioPriority: belowNormal
